CapstoneProject-master/BlogTracker/BlogTracker/Controllers/BlogInfoesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BlogTracker.Data;
using BlogTracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace BlogTracker.Controllers
{

    public class BlogInfoesController : Controller
    {
        private readonly BlogTrackerDbContext _context;

        public BlogInfoesController(BlogTrackerDbContext context)
        {
            _context = context;
        }

        // GET: BlogInfoes
        public async Task<IActionResult> Index()
        {
              return _context.BlogInfo != null ? 
                          View(await _context.BlogInfo.ToListAsync()) :
                          Problem("Entity set 'BlogTrackerDbContext.BlogInfo'  is null.");
        }

        public async Task<IActionResult> EmployeeBlogIndex()
        {
            return _context.BlogInfo != null ?
                        View(await _context.BlogInfo.ToListAsync()) :
                        Problem("Entity set 'BlogTrackerDbContext.BlogInfo'  is null.");
        }

        // GET: BlogInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BlogInfo == null)
            {
                return NotFound();
            }

            var blogInfo = await _context.BlogInfo
                .FirstOrDefaultAsync(m => m.BlogInfoId == id);
            if (blogInfo == null)
            {
                return NotFound();
            }

            return View(blogInfo);
        }


        // GET: BlogInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BlogInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogInfoId,Title,Subject,DateOfCreation,BlogUrl,EmpEmailId")] BlogInfo blogInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blogInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blogInfo);
        }

        // GET: BlogInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BlogInfo == null)
            {
                return NotFound();
            }

            var blogInfo = await _context.BlogInfo.FindAsync(id);
            if (blogInfo == null)
            {
                return NotFound();
            }
            return View(blogInfo);
        }

        // POST: BlogInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BlogInfoId,Title,Subject,DateOfCreation,BlogUrl,EmpEmailId")] BlogInfo blogInfo)
        {
            if (id != blogInfo.BlogInfoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blogInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogInfoExists(blogInfo.BlogInfoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blogInfo);
        }

        // GET: BlogInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BlogInfo == null)
            {
                return NotFound();
            }

            var blogInfo = await _context.BlogInfo
                .FirstOrDefaultAsync(m => m.BlogInfoId == id);
            if (blogInfo == null)
            {
                return NotFound();
            }

            return View(blogInfo);
        }

        // POST: BlogInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BlogInfo == null)
            {
                return Problem("Entity set 'BlogTrackerDbContext.BlogInfo'  is null.");
            }
            var blogInfo = await _context.BlogInfo.FindAsync(id);
            if (blogInfo != null)
            {
                _context.BlogInfo.Remove(blogInfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogInfoExists(int id)
        {
          return (_context.BlogInfo?.Any(e => e.BlogInfoId == id)).GetValueOrDefault();
        }
    }
}

CapstoneProject-master/BlogTracker/BlogTracker/Controllers/EmpInfoesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BlogTracker.Data;
using BlogTracker.Models;

namespace BlogTracker.Controllers
{
    public class EmpInfoesController : Controller
    {
        private readonly BlogTrackerDbContext _context;

        public EmpInfoesController(BlogTrackerDbContext context)
        {
            _context = context;
        }

        // Employee Login action
        public IActionResult EmployeeLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EmployeeLogin(string emailId, int passCode)
        {
            // Implement authentication logic here
            var employee = _context.EmpInfo.FirstOrDefault(e => e.EmailId == emailId && e.PassCode == passCode);

            if (employee != null)
            {
                // Set a session or cookie to mark the employee as logged in
                HttpContext.Session.SetString("EmployeeEmail", employee.EmailId);

                return RedirectToAction("EmployeeBlogIndex", "BlogInfoes");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return View();
            }
        }

        // Employee Logout action
        public IActionResult Logout()
        {
            // Clear the session or cookie to log the employee out
            HttpContext.Session.Remove("EmployeeEmail");
            return RedirectToAction("Index", "BlogInfoes");
        }

        // GET: EmpInfoes
        public async Task<IActionResult> Index()
        {
              return _context.EmpInfo != null ? 
                          View(await _context.EmpInfo.ToListAsync()) :
                          Problem("Entity set 'BlogTrackerDbContext.EmpInfo'  is null.");
        }

        // GET: EmpInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.EmpInfo == null)
            {
                return NotFound();
            }

            var empInfo = await _context.EmpInfo
                .FirstOrDefaultAsync(m => m.EmpInfoId == id);
            if (empInfo == null)
            {
                return NotFound();
            }

            return View(empInfo);
        }

        // GET: EmpInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EmpInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmpInfoId,EmailId,Name,DateOfJoining,PassCode")] EmpInfo empInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empInfo);
        }

        // GET: EmpInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.EmpInfo == null)
            {
                return NotFound();
            }

            var empInfo = await _context.EmpInfo.FindAsync(id);
            if (empInfo == null)
            {
                return NotFound();
            }
            return View(empInfo);
        }

        // POST: EmpInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmpInfoId,EmailId,Name,DateOfJoining,PassCode")] EmpInfo empInfo)
        {
            if (id != empInfo.EmpInfoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpInfoExists(empInfo.EmpInfoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empInfo);
        }

        // GET: EmpInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.EmpInfo == null)
            {
                return NotFound();
            }

            var empInfo = await _context.EmpInfo
                .FirstOrDefaultAsync(m => m.EmpInfoId == id);
            if (empInfo == null)
            {
                return NotFound();
            }

            return View(empInfo);
        }

        // POST: EmpInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.EmpInfo == null)
            {
                return Problem("Entity set 'BlogTrackerDbContext.EmpInfo'  is null.");
            }
            var empInfo = await _context.EmpInfo.FindAsync(id);
            if (empInfo != null)
            {
                _context.EmpInfo.Remove(empInfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpInfoExists(int id)
        {
          return (_context.EmpInfo?.Any(e => e.EmpInfoId == id)).GetValueOrDefault();
        }
    }
}

CapstoneProject-master/BlogTracker/BlogTracker/Views/BlogInfoes/Create.cshtml
@model BlogTracker.Models.BlogInfo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BlogInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfCreation" class="control-label"></label>
                <input asp-for="DateOfCreation" class="form-control" />
                <span asp-validation-for="DateOfCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogUrl" class="control-label"></label>
                <input asp-for="BlogUrl" class="form-control" />
                <span asp-validation-for="BlogUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpEmailId" class="control-label"></label>
                <input asp-for="EmpEmailId" class="form-control" />
                <span asp-validation-for="EmpEmailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CapstoneProject-master/BlogTracker/BlogTracker/Views/BlogInfoes/Delete.cshtml
@model BlogTracker.Models.BlogInfo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfCreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfCreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BlogUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BlogUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmpEmailId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmpEmailId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BlogInfoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CapstoneProject-master/BlogTracker/BlogTracker/Views/BlogInfoes/Details.cshtml
@model BlogTracker.Models.BlogInfo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BlogInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfCreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfCreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BlogUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BlogUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmpEmailId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmpEmailId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BlogInfoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CapstoneProject-master/BlogTracker/BlogTracker/Views/BlogInfoes/Edit.cshtml
@model BlogTracker.Models.BlogInfo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BlogInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BlogInfoId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfCreation" class="control-label"></label>
                <input asp-for="DateOfCreation" class="form-control" />
                <span asp-validation-for="DateOfCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogUrl" class="control-label"></label>
                <input asp-for="BlogUrl" class="form-control" />
                <span asp-validation-for="BlogUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpEmailId" class="control-label"></label>
                <input asp-for="EmpEmailId" class="form-control" />
                <span asp-validation-for="EmpEmailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CapstoneProject-master/BlogTracker/BlogTracker/Views/BlogInfoes/EmployeeBlogIndex.cshtml
@model IEnumerable<BlogTracker.Models.BlogInfo>
@{
    ViewData["Title"] = "EmployeeBlogIndex";
}

<h1>EmployeeBlogIndex</h1>

<p>
    <a asp-action="Create" class="btn btn-dark">Create New</a>&nbsp;&nbsp;<a asp-controller="EmpInfoes" asp-action="Logout" class="btn btn-warning">Logout</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfCreation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BlogUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmpEmailId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfCreation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BlogUrl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmpEmailId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.BlogInfoId" class="btn btn-primary">Edit</a> |
                     
                    <a asp-action="Delete" asp-route-id="@item.BlogInfoId" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

CapstoneProject-master/BlogTracker/BlogTracker/Views/BlogInfoes/Index.cshtml
@model IEnumerable<BlogTracker.Models.BlogInfo>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Blog Info</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfCreation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BlogUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmpEmailId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfCreation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BlogUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmpEmailId)
            </td>
        </tr>
}
    </tbody>
</table>